include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = PlampyCC
PlampyCC_FILES = RootListController.m
PlampyCC_INSTALL_PATH = /Library/PreferenceBundles
PlampyCC_FRAMEWORKS = UIKit
include $(THEOS_MAKE_PATH)/bundle.mk
