include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = PlampyCC
PlampyCC_FILES = RootListController.m
PlampyCC_INSTALL_PATH = $(THEOS_PACKAGE_INSTALL_PREFIX)/Library/PreferenceBundles
PlampyCC_FRAMEWORKS = UIKit
PlampyCC_PRIVATE_FRAMEWORKS = Preferences
include $(THEOS_MAKE_PATH)/bundle.mk
